subscribe_urls:
  - https://raw.githubusercontent.com/NiceVPN123/NiceVPN/main/utils/pool/output.yaml
  - https://raw.githubusercontent.com/SamanGho/v2ray_collector/main/v2tel_links2.txt
  - https://raw.githubusercontent.com/SamanGho/v2ray_collector/main/v2tel_links1.txt

timeout: 8000
concurrent: 40
min-speed: 0.5
download-timeout: 10
download-mb: 5
max-delay: 3000
speed-test-url: "http://speed.cloudflare.com/_down"

sort-by: speed
rename-format: "{emoji}{country}_{id} |{speed}|{delay}ms|{yt}|{nf}|{dplus}|{gpt}|{tk}"

output_file: output/all.yaml
log_file: logs/subscription_summary.log