subscribe_urls:
  - https://raw.githubusercontent.com/NiceVPN123/NiceVPN/main/utils/pool/output.yaml
  - https://raw.githubusercontent.com/SamanGho/v2ray_collector/main/v2tel_links2.txt
  - https://raw.githubusercontent.com/SamanGho/v2ray_collector/main/v2tel_links1.txt

timeout: 5000
concurrent: 50
min-speed: 0.5
max-delay: 1500
download-timeout: 10
download-mb: 5

speed-test-url: https://github.com/AaronFeng753/Waifu2x-Extension-GUI/releases/download/v2.21.12/Waifu2x-Extension-GUI-v2.21.12-Portable.7z

rename-format: "{emoji}{country}_{id} |{speed}|{delay}ms|{yt}|{nf}|{dplus}|{gpt}|{tk}"
sort-by: delay

output_file: output/all.yaml