concurrent: 100
timeout: 5
global_timeout: 20
max_delay: 1000
min_speed_kbps: 300
download_size_kb: 1024

test_gpt: true
test_youtube: true
test_netflix: true
test_disney: true
test_tiktok: true

rename_format: "{emoji}{country}_{id} |{speed}|{loss}|{yt}|{nf}|{d+}|{gpt}|{tk}"
sort_by: speed